//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DEMO_FIRST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARTICLE_DBEntities : DbContext
    {
        public ARTICLE_DBEntities()
            : base("name=ARTICLE_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_articles> t_articles { get; set; }
        public virtual DbSet<t_category> t_category { get; set; }
        public virtual DbSet<t_users> t_users { get; set; }
        public virtual DbSet<v_get_articles> v_get_articles { get; set; }
    }
}
