//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DEMO_FIRST
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_users()
        {
            this.t_articles = new HashSet<t_articles>();
        }
    
        public int id { get; set; }
        public string zh_name { get; set; }
        public string name { get; set; }
        public string pwd { get; set; }
        public string roles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_articles> t_articles { get; set; }
    }
}
