//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DEMO_FIRST
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_get_articles
    {
        public int id { get; set; }
        public Nullable<int> cate_id { get; set; }
        public string cate_name { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<int> create_user { get; set; }
        public string user_name { get; set; }
    }
}
