//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleDemo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ARTICLE_DBEntities : DbContext
    {
        public ARTICLE_DBEntities()
            : base("name=ARTICLE_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_articles> t_articles { get; set; }
        public virtual DbSet<t_category> t_category { get; set; }
        public virtual DbSet<T_ROLES> T_ROLES { get; set; }
        public virtual DbSet<t_users> t_users { get; set; }
        public virtual DbSet<TEST> TEST { get; set; }
        public virtual DbSet<v_get_articles> v_get_articles { get; set; }
    
        public virtual int proc_add_test_data()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_add_test_data");
        }
    
        public virtual int sp_paged_data(string sqlTable, string sqlColumns, string sqlWhere, string sqlSort, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter rowTotal)
        {
            var sqlTableParameter = sqlTable != null ?
                new ObjectParameter("sqlTable", sqlTable) :
                new ObjectParameter("sqlTable", typeof(string));
    
            var sqlColumnsParameter = sqlColumns != null ?
                new ObjectParameter("sqlColumns", sqlColumns) :
                new ObjectParameter("sqlColumns", typeof(string));
    
            var sqlWhereParameter = sqlWhere != null ?
                new ObjectParameter("sqlWhere", sqlWhere) :
                new ObjectParameter("sqlWhere", typeof(string));
    
            var sqlSortParameter = sqlSort != null ?
                new ObjectParameter("sqlSort", sqlSort) :
                new ObjectParameter("sqlSort", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_paged_data", sqlTableParameter, sqlColumnsParameter, sqlWhereParameter, sqlSortParameter, pageIndexParameter, pageSizeParameter, rowTotal);
        }
    
        public virtual int SP_PAGING(string tABLES, string pRIMARYKEY, string sORT, Nullable<int> pAGEINDEX, Nullable<int> pAGESIZE, string fIELDS, string fILTER, string gROUP, ObjectParameter tOTALCOUNT)
        {
            var tABLESParameter = tABLES != null ?
                new ObjectParameter("TABLES", tABLES) :
                new ObjectParameter("TABLES", typeof(string));
    
            var pRIMARYKEYParameter = pRIMARYKEY != null ?
                new ObjectParameter("PRIMARYKEY", pRIMARYKEY) :
                new ObjectParameter("PRIMARYKEY", typeof(string));
    
            var sORTParameter = sORT != null ?
                new ObjectParameter("SORT", sORT) :
                new ObjectParameter("SORT", typeof(string));
    
            var pAGEINDEXParameter = pAGEINDEX.HasValue ?
                new ObjectParameter("PAGEINDEX", pAGEINDEX) :
                new ObjectParameter("PAGEINDEX", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            var fIELDSParameter = fIELDS != null ?
                new ObjectParameter("FIELDS", fIELDS) :
                new ObjectParameter("FIELDS", typeof(string));
    
            var fILTERParameter = fILTER != null ?
                new ObjectParameter("FILTER", fILTER) :
                new ObjectParameter("FILTER", typeof(string));
    
            var gROUPParameter = gROUP != null ?
                new ObjectParameter("GROUP", gROUP) :
                new ObjectParameter("GROUP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PAGING", tABLESParameter, pRIMARYKEYParameter, sORTParameter, pAGEINDEXParameter, pAGESIZEParameter, fIELDSParameter, fILTERParameter, gROUPParameter, tOTALCOUNT);
        }
    }
}
