//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_articles
    {
        public int id { get; set; }
        public Nullable<int> cate_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<int> create_user { get; set; }
    
        public virtual t_category t_category { get; set; }
        public virtual t_users t_users { get; set; }
    }
}
